const mongoose =require('mongoose');
const Schema=mongoose.Schema;
const userSchema=new Schema({
name:{
    type:'string',
    required:true
},
username:{
    type:'string',
    required:true
},
email:{
    type:'string',
    required:true
},
password:{
    type:'string',
    required:true
},
role:{
    type:'string',
    required:true
},
password:{
    type:'string',
    required:true
},
status:{
    type:'string',
    required:true
},
resetPasswordToken:{
    type:'string',
},
resetPasswordExpires:{
    type:'string',
}
},{collection:'User'});
mongoose.model('User',userSchema);